Location: ErrorCheckTest.java

Content: 

protected void launchTest(String filename) throws Exception {

  try {

    setUp(filename);

    fail("Expected ValidationException to be thrown");

  }

 catch (  LoadingException e) {

    assertTrue(e.getCause() instanceof ValidationException);

  }

}

