Location: FunctorException.java

Content: 

/** 

 * Constructs a new  {@code FunctorException} without specifieddetail message.

 */

public FunctorException(){

}

Location: FunctorException.java

Content: 

/** 

 * Constructs a new  {@code FunctorException} with specifieddetail message.

 * @param msg  the error message.

 */

public FunctorException(final String msg){

  super(msg);

}

Location: FunctorException.java

Content: 

/** 

 * Constructs a new  {@code FunctorException} with specifieddetail message and nested  {@code Throwable} root cause.

 * @param msg        the error message.

 * @param rootCause  the exception or error that caused this exceptionto be thrown.

 */

public FunctorException(final String msg,final Throwable rootCause){

  super(msg,rootCause);

}

Location: FunctorException.java

Content: 

/** 

 * Constructs a new  {@code FunctorException} with specifiednested  {@code Throwable} root cause.

 * @param rootCause  the exception or error that caused this exceptionto be thrown.

 */

public FunctorException(final Throwable rootCause){

  super(rootCause);

}

Location: FunctorException.java

Content: 

/** 

 * Constructs a new  {@code FunctorException} without specifieddetail message.

 */

public FunctorException(){

}

Location: FunctorException.java

Content: 

/** 

 * Constructs a new  {@code FunctorException} with specifieddetail message.

 * @param msg  the error message.

 */

public FunctorException(final String msg){

  super(msg);

}

Location: FunctorException.java

Content: 

/** 

 * Constructs a new  {@code FunctorException} with specifieddetail message and nested  {@code Throwable} root cause.

 * @param msg        the error message.

 * @param rootCause  the exception or error that caused this exceptionto be thrown.

 */

public FunctorException(final String msg,final Throwable rootCause){

  super(msg,rootCause);

}

Location: FunctorException.java

Content: 

/** 

 * Constructs a new  {@code FunctorException} with specifiednested  {@code Throwable} root cause.

 * @param rootCause  the exception or error that caused this exceptionto be thrown.

 */

public FunctorException(final Throwable rootCause){

  super(rootCause);

}

